'use client'

import { useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import {
  addTranscript,
  replaceTranscript,
  removeTranscript,
  getTranscriptContent,
  checkGoogleMeetTranscript,
} from '@/lib/actions/transcripts'
import type { TranscriptSource } from '@/lib/actions/transcripts'

type Props = {
  meetingId:    string
  initialFile:  TranscriptSource | null
  canManage:    boolean
  canRead:      boolean
  /** meet_space_name from the meeting row — enables "Check for transcript" when set. */
  meetSpaceName: string | null
}

const ACCEPT  = '.vtt,.srt,.txt,.md'
const MAX_MB  = 5

type InputMode = 'file-add' | 'file-replace' | 'paste-add' | 'paste-replace' | null

type CheckState =
  | 'idle'
  | 'checking'
  | 'processing'   // transcript still being generated by Google
  | 'not_found'
  | 'ambiguous'
  | 'conflict'     // a different transcript is already attached
  | 'error'

export default function TranscriptSection({
  meetingId,
  initialFile,
  canManage,
  canRead,
  meetSpaceName,
}: Props) {
  const router  = useRouter()
  const fileRef = useRef<HTMLInputElement>(null)

  const [mode,      setMode]      = useState<InputMode>(null)
  const [pasteText, setPasteText] = useState('')
  const [busy,      setBusy]      = useState(false)
  const [error,     setError]     = useState<string | null>(null)

  // Google Meet check state
  const [checkState,   setCheckState]   = useState<CheckState>('idle')
  const [checkMessage, setCheckMessage] = useState<string | null>(null)
  const [conflictSource, setConflictSource] = useState<TranscriptSource | null>(null)

  // View state — content loaded on demand
  const [viewOpen,    setViewOpen]    = useState(false)
  const [viewContent, setViewContent] = useState<string | null>(null)
  const [viewLoading, setViewLoading] = useState(false)
  const [viewError,   setViewError]   = useState<string | null>(null)

  // ── view transcript ────────────────────────────────────────────────────────

  async function handleToggleView() {
    if (viewOpen) {
      setViewOpen(false)
      return
    }
    // Load content on first open (or after a replace/remove cycle resets it)
    if (!viewContent) {
      setViewLoading(true)
      setViewError(null)
      const result = await getTranscriptContent(meetingId)
      if ('error' in result) {
        setViewError(result.error)
        setViewLoading(false)
        return
      }
      setViewContent(result.content)
      setViewLoading(false)
    }
    setViewOpen(true)
  }

  function resetView() {
    setViewOpen(false)
    setViewContent(null)
    setViewError(null)
  }

  // ── file upload ────────────────────────────────────────────────────────────

  function triggerFile(m: 'file-add' | 'file-replace') {
    setMode(m)
    setError(null)
    fileRef.current?.click()
  }

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file || (mode !== 'file-add' && mode !== 'file-replace')) return

    if (file.size > MAX_MB * 1024 * 1024) {
      setError(`File is too large. Maximum size is ${MAX_MB} MB.`)
      resetFileInput()
      return
    }

    setBusy(true)
    setError(null)

    let content: string
    try {
      content = await file.text()
    } catch {
      setError('Could not read the file. Please try again.')
      setBusy(false)
      resetFileInput()
      return
    }

    const action = mode === 'file-add' ? addTranscript : replaceTranscript
    const result = await action(meetingId, file.name, content)

    if (result.error) {
      setError(result.error)
    } else {
      resetView()
      router.refresh()
    }

    setBusy(false)
    resetFileInput()
  }

  function resetFileInput() {
    setMode(null)
    if (fileRef.current) fileRef.current.value = ''
  }

  // ── paste ──────────────────────────────────────────────────────────────────

  function openPaste(m: 'paste-add' | 'paste-replace') {
    setMode(m)
    setPasteText('')
    setError(null)
  }

  function cancelPaste() {
    setMode(null)
    setPasteText('')
    setError(null)
  }

  async function handlePasteSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!pasteText.trim() || (mode !== 'paste-add' && mode !== 'paste-replace')) return

    setBusy(true)
    setError(null)

    const action = mode === 'paste-add' ? addTranscript : replaceTranscript
    const result = await action(meetingId, null, pasteText)

    if (result.error) {
      setError(result.error)
      setBusy(false)
    } else {
      setMode(null)
      setPasteText('')
      resetView()
      router.refresh()
    }
  }

  // ── remove ─────────────────────────────────────────────────────────────────

  async function handleRemove() {
    setBusy(true)
    setError(null)
    const result = await removeTranscript(meetingId)
    if (result.error) {
      setError(result.error)
    } else {
      resetView()
      router.refresh()
    }
    setBusy(false)
  }

  // ── Google Meet transcript check ───────────────────────────────────────────

  async function handleCheckMeetTranscript(replaceExisting = false) {
    setBusy(true)
    setCheckState('checking')
    setCheckMessage(null)
    setConflictSource(null)
    setError(null)

    const response = await checkGoogleMeetTranscript(meetingId, replaceExisting)

    if ('error' in response) {
      setCheckState('error')
      setCheckMessage(response.error)
      setBusy(false)
      return
    }

    const { result } = response

    switch (result.status) {
      case 'attached':
        resetView()
        setCheckState('idle')
        router.refresh()
        break
      case 'already_attached':
        setCheckState('idle')
        router.refresh()
        break
      case 'conflict':
        setCheckState('conflict')
        setConflictSource(result.existingSource)
        break
      case 'processing':
        setCheckState('processing')
        break
      case 'not_found':
        setCheckState('not_found')
        setCheckMessage(result.reason)
        break
      case 'ambiguous':
        setCheckState('ambiguous')
        break
    }

    setBusy(false)
  }

  // ── display helpers ────────────────────────────────────────────────────────

  function formatBytes(bytes: number | null): string {
    if (!bytes) return ''
    if (bytes < 1024) return `${bytes} B`
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`
    return `${(bytes / 1024 / 1024).toFixed(1)} MB`
  }

  function formatChars(chars: number | null): string {
    if (!chars) return ''
    if (chars >= 1000) return `${(chars / 1000).toFixed(1)}k chars`
    return `${chars} chars`
  }

  function formatDate(iso: string): string {
    return new Date(iso).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'short', year: 'numeric',
    })
  }

  const isPasteMode = mode === 'paste-add' || mode === 'paste-replace'

  return (
    <div className="bg-kk-panel border border-kk-line rounded-2xl">
      <div className="px-5 py-4 border-b border-kk-line">
        <h2 className="text-sm font-semibold text-kk-ink">Transcript</h2>
      </div>

      <div className="px-5 py-4 space-y-3">
        {/* Current transcript metadata */}
        {initialFile && (
          <div className="flex items-start gap-2">
            {initialFile.provider === 'google_meet' ? (
              <span className="mt-0.5 text-xs font-medium text-kk-good bg-kk-good-bg border border-kk-good rounded px-1.5 py-0.5 shrink-0 leading-none whitespace-nowrap">
                Google Meet
              </span>
            ) : (
              <span className="mt-0.5 text-xs font-medium text-kk-muted bg-kk-soft border border-kk-line rounded px-1.5 py-0.5 shrink-0 leading-none uppercase">
                {initialFile.format}
              </span>
            )}
            <div className="flex-1 min-w-0">
              <div className="text-sm text-kk-ink break-words leading-snug">
                {initialFile.provider === 'google_meet'
                  ? 'Google Meet transcript'
                  : (initialFile.fileName ?? 'Pasted transcript')}
              </div>
              <div className="text-xs text-kk-muted mt-0.5 space-x-1">
                <span>Attached {formatDate(initialFile.attachedAt)}</span>
                {initialFile.provider === 'google_meet' ? (
                  <>
                    {initialFile.wordCount
                      ? <span>· {initialFile.wordCount.toLocaleString()} words</span>
                      : null}
                    {initialFile.speakerCount
                      ? <span>· {initialFile.speakerCount} {initialFile.speakerCount === 1 ? 'speaker' : 'speakers'}</span>
                      : null}
                    {initialFile.languageCode
                      ? <span>· {initialFile.languageCode}</span>
                      : null}
                  </>
                ) : (
                  <>
                    {initialFile.charCount
                      ? <span>· {formatChars(initialFile.charCount)}</span>
                      : initialFile.byteSize
                        ? <span>· {formatBytes(initialFile.byteSize)}</span>
                        : null}
                    {initialFile.provider === 'manual_paste' && (
                      <span>· pasted</span>
                    )}
                  </>
                )}
              </div>
            </div>
          </div>
        )}

        {/* View transcript toggle */}
        {initialFile && canRead && !isPasteMode && (
          <button
            onClick={handleToggleView}
            disabled={viewLoading}
            className="text-xs text-kk-muted hover:text-kk-ink transition-colors disabled:opacity-40"
          >
            {viewLoading ? 'Loading…' : viewOpen ? 'Hide transcript' : 'View transcript'}
          </button>
        )}

        {/* Inline transcript viewer */}
        {viewOpen && viewContent && (
          <pre className="text-xs text-kk-ink whitespace-pre-wrap font-mono bg-kk-soft border border-kk-line rounded-xl px-4 py-3 max-h-80 overflow-y-auto leading-relaxed">
            {viewContent}
          </pre>
        )}

        {viewError && (
          <p className="text-xs text-kk-bad">{viewError}</p>
        )}

        {/* Manage buttons — shown when a transcript exists */}
        {initialFile && canManage && !isPasteMode && (
          <div className="flex items-center gap-3 pt-1">
            <button
              onClick={() => triggerFile('file-replace')}
              disabled={busy}
              className="text-xs text-kk-muted hover:text-kk-ink transition-colors disabled:opacity-40"
            >
              {busy && mode === 'file-replace' ? 'Uploading…' : 'Replace file'}
            </button>
            <button
              onClick={() => openPaste('paste-replace')}
              disabled={busy}
              className="text-xs text-kk-muted hover:text-kk-ink transition-colors disabled:opacity-40"
            >
              Replace with paste
            </button>
            <button
              onClick={handleRemove}
              disabled={busy}
              className="text-xs text-kk-muted hover:text-kk-bad transition-colors disabled:opacity-40"
            >
              {busy && mode === null ? 'Removing…' : 'Remove'}
            </button>
          </div>
        )}

        {/* Google Meet check section — shown when a Meet space is linked */}
        {meetSpaceName && canManage && !isPasteMode && (
          <div className="space-y-2">
            {/* Idle: show check button */}
            {checkState === 'idle' && (
              <button
                onClick={() => handleCheckMeetTranscript(false)}
                disabled={busy}
                className="text-sm text-kk-ink underline hover:opacity-70 transition-opacity disabled:opacity-40"
              >
                Check for transcript
              </button>
            )}

            {/* Checking */}
            {checkState === 'checking' && (
              <p className="text-sm text-kk-muted">Checking Google Meet…</p>
            )}

            {/* Still processing */}
            {checkState === 'processing' && (
              <div className="space-y-1">
                <p className="text-xs text-kk-muted">
                  Google is still processing the transcript. Check again in a few minutes.
                </p>
                <button
                  onClick={() => handleCheckMeetTranscript(false)}
                  disabled={busy}
                  className="text-xs text-kk-ink underline hover:opacity-70 transition-opacity disabled:opacity-40"
                >
                  Check again
                </button>
              </div>
            )}

            {/* Not found */}
            {checkState === 'not_found' && (
              <div className="space-y-1">
                <p className="text-xs text-kk-muted">
                  No Google Meet transcript was found for this meeting.
                </p>
                {checkMessage && (
                  <p className="text-xs text-kk-muted">{checkMessage}</p>
                )}
                <button
                  onClick={() => setCheckState('idle')}
                  className="text-xs text-kk-muted underline hover:text-kk-ink transition-colors"
                >
                  Try again
                </button>
              </div>
            )}

            {/* Ambiguous conference records */}
            {checkState === 'ambiguous' && (
              <div className="space-y-1">
                <p className="text-xs text-kk-muted">
                  Multiple conference records were found for this meeting. Please contact support if this persists.
                </p>
                <button
                  onClick={() => setCheckState('idle')}
                  className="text-xs text-kk-muted underline hover:text-kk-ink transition-colors"
                >
                  Dismiss
                </button>
              </div>
            )}

            {/* Conflict with existing transcript */}
            {checkState === 'conflict' && conflictSource && (
              <div className="p-3 rounded-xl bg-amber-50 border border-amber-200 space-y-2">
                <p className="text-xs text-amber-700">
                  A transcript is already attached to this meeting. Replace it with the Google Meet transcript?
                </p>
                <div className="flex items-center gap-3">
                  <button
                    onClick={() => handleCheckMeetTranscript(true)}
                    disabled={busy}
                    className="text-xs text-amber-700 font-medium underline hover:opacity-70 transition-opacity disabled:opacity-40"
                  >
                    {busy ? 'Replacing…' : 'Use Google transcript'}
                  </button>
                  <button
                    onClick={() => { setCheckState('idle'); setConflictSource(null) }}
                    disabled={busy}
                    className="text-xs text-kk-muted hover:text-kk-ink transition-colors disabled:opacity-40"
                  >
                    Keep current
                  </button>
                </div>
              </div>
            )}

            {/* Error state */}
            {checkState === 'error' && checkMessage && (
              <div className="space-y-1">
                <p className="text-xs text-kk-bad">{checkMessage}</p>
                <button
                  onClick={() => setCheckState('idle')}
                  className="text-xs text-kk-muted underline hover:text-kk-ink transition-colors"
                >
                  Try again
                </button>
              </div>
            )}
          </div>
        )}

        {/* No transcript yet — attach options */}
        {!initialFile && canManage && !isPasteMode && (
          <div className="flex items-center gap-3">
            <button
              onClick={() => triggerFile('file-add')}
              disabled={busy}
              className="text-sm text-kk-muted hover:text-kk-ink transition-colors disabled:opacity-40"
            >
              {busy && mode === 'file-add' ? 'Uploading…' : '+ Attach file'}
            </button>
            <span className="text-xs text-kk-muted">or</span>
            <button
              onClick={() => openPaste('paste-add')}
              disabled={busy}
              className="text-sm text-kk-muted hover:text-kk-ink transition-colors disabled:opacity-40"
            >
              Paste text
            </button>
          </div>
        )}

        {/* No transcript, read-only */}
        {!initialFile && !canManage && (
          <p className="text-sm text-kk-muted">No transcript attached.</p>
        )}

        {/* Paste textarea */}
        {isPasteMode && (
          <form onSubmit={handlePasteSubmit} className="space-y-2">
            <textarea
              value={pasteText}
              onChange={(e) => setPasteText(e.target.value)}
              placeholder="Paste transcript text here…"
              rows={8}
              className="w-full text-sm px-3 py-2 bg-kk-soft border border-kk-line rounded-xl placeholder:text-kk-muted focus:outline-none focus:ring-2 focus:ring-kk-ink/20 resize-y font-mono"
              disabled={busy}
              autoFocus
            />
            <div className="flex items-center gap-2">
              <button
                type="submit"
                disabled={busy || !pasteText.trim()}
                className="px-3 py-1.5 bg-kk-ink text-white text-sm rounded-xl disabled:opacity-40 hover:opacity-90 transition-opacity"
              >
                {busy ? 'Attaching…' : 'Attach transcript'}
              </button>
              <button
                type="button"
                onClick={cancelPaste}
                disabled={busy}
                className="text-sm text-kk-muted hover:text-kk-ink transition-colors disabled:opacity-40"
              >
                Cancel
              </button>
            </div>
          </form>
        )}

        {error && (
          <p className="text-xs text-kk-bad">{error}</p>
        )}

        {/* Hidden file input */}
        <input
          ref={fileRef}
          type="file"
          accept={ACCEPT}
          className="hidden"
          onChange={handleFileChange}
        />
      </div>
    </div>
  )
}
