/**
 * components/ui/MarkdownMeetingMinutes.tsx
 *
 * Read-only markdown renderer for meeting minutes.
 *
 * Handles the formatting patterns generated by the AI and written by humans:
 *   # / ## / ###  → headings
 *   - or *        → bullet list items
 *   **text**      → bold inline
 *   blank lines   → paragraph breaks
 *   everything else → paragraph text
 *
 * Safety: All text passes through React's VDOM as text nodes — no
 * dangerouslySetInnerHTML, no raw HTML injection, no script execution.
 */

import type { ReactNode } from 'react'

/** Split a line on **bold** markers; returns an array of strings and <strong> nodes. */
function renderInline(text: string): ReactNode[] {
  const segments = text.split(/(\*\*[^*]+\*\*)/)
  return segments.map((seg, i) => {
    if (seg.startsWith('**') && seg.endsWith('**')) {
      return <strong key={i} className="font-semibold">{seg.slice(2, -2)}</strong>
    }
    return seg
  })
}

export function MarkdownMeetingMinutes({ body }: { body: string }) {
  const lines = body.split('\n')
  const elements: ReactNode[] = []
  let listItems: string[] = []
  let key = 0

  function flushList() {
    if (listItems.length === 0) return
    const items = listItems.splice(0)
    elements.push(
      <ul key={key++} className="list-disc pl-5 my-2 space-y-0.5">
        {items.map((item, i) => (
          <li key={i} className="text-sm text-kk-ink">{renderInline(item)}</li>
        ))}
      </ul>
    )
  }

  for (const line of lines) {
    const h1 = line.match(/^# (.+)/)
    const h2 = line.match(/^## (.+)/)
    const h3 = line.match(/^### (.+)/)
    const li = line.match(/^[*-] (.+)/)

    if (h1) {
      flushList()
      elements.push(
        <h2 key={key++} className="text-base font-black text-kk-ink mt-5 mb-1 first:mt-0">
          {renderInline(h1[1])}
        </h2>
      )
    } else if (h2) {
      flushList()
      elements.push(
        <h3 key={key++} className="text-sm font-bold text-kk-ink mt-4 mb-1 first:mt-0">
          {renderInline(h2[1])}
        </h3>
      )
    } else if (h3) {
      flushList()
      elements.push(
        <h4 key={key++} className="text-sm font-semibold text-kk-ink mt-3 mb-0.5 first:mt-0">
          {renderInline(h3[1])}
        </h4>
      )
    } else if (li) {
      listItems.push(li[1])
    } else if (line.trim() === '') {
      flushList()
    } else {
      flushList()
      elements.push(
        <p key={key++} className="text-sm text-kk-ink leading-relaxed">
          {renderInline(line)}
        </p>
      )
    }
  }
  flushList()

  return <div className="space-y-2">{elements}</div>
}
